Repository sungwon2598/moya, pull requests merged in 2024-11, with the labels that each got.

#6 #3 KAN-76 메인페이지 UI
  front/src/App.tsx
  front/src/component/Feature.tsx
  front/src/context/AuthContext.tsx
  front/src/layout/RootLayout.tsx
  front/src/layout/header/Header.tsx
  front/src/layout/header/NavItem.tsx
  front/src/main.tsx
  front/src/pages/main/Main.tsx
  front/src/pages/main/MainContent.tsx
  front/src/routes/index.tsx
  front/src/types/types.tsx
  front/tailwind.config.js
  front/tsconfig.app.json
Labels: enhancement, frontend, page

#13 KAN-87--footer
  front/package.json
  front/src/data/footerData.ts
  front/src/index.css
  front/src/layout/RootLayout.tsx
  front/src/layout/footer/Footer.tsx
  front/src/layout/footer/FooterComponents.tsx
  front/src/layout/footer/FooterSection.tsx
  front/src/types/footer.ts
Labels: enhancement, frontend

#22 KAN-102 feat: fe deploy yml 파일 추가
  .github/workflows/frontend-deploy.yml
Labels: frontend

#17 [FE] [KAN-91] 로드맵 미리보기 페이지 구현
  front/src/component/roadmap/RoadmapCard.tsx
  front/src/data/roadmap-samples.ts
  front/src/pages/RoadmapPreview.tsx
  front/src/pages/main/MainContent.tsx
  front/src/routes/index.tsx
  front/src/types/roadmap.ts
Labels: enhancement, frontend

#43 [FIX] [FE] KAN-91 잘못된 임포트 내용 수정
  front/src/routes/index.tsx
Labels: bug

#46 [FE] [FEAT] KAN-103 채팅방 구현
  back/moya/src/main/java/com/study/moya/chat/text/dto/chatroom/ChatRoomDTO.java
  front/.env.development
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/component/common/chat/Button.tsx
  front/src/component/common/chat/ChatList/index.tsx
  front/src/component/common/chat/ChatRoom/ChatHeader.tsx
  front/src/component/common/chat/ChatRoom/ChatInput.tsx
  front/src/component/common/chat/ChatRoom/ChatMessage.tsx
  front/src/component/common/chat/ChatRoom/MessageList.tsx
  front/src/component/common/chat/ChatRoom/index.tsx
  front/src/component/common/chat/ErrorMessage.tsx
  front/src/component/common/chat/Input.tsx
  front/src/component/common/chat/LoadingSpinner.tsx
  front/src/config/apiConfig.ts
  front/src/context/AuthContext.tsx
  front/src/layout/header/Header.tsx
  front/src/layout/header/NavItem.tsx
  front/src/main.tsx
  front/src/pages/chat/ChatList.tsx
  front/src/pages/chat/ChatRoom.tsx
  front/src/pages/main/Main.tsx
  front/src/routes/index.tsx
  front/src/types/chat.ts
  front/src/types/types.tsx
  front/src/utils/cn.ts
  front/tsconfig.json
Labels: enhancement, frontend
